apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: tyler-test
  description: tyler-testing group
spec:
  type: business-unit
  profile:
    displayName: Infrastructure
    email: infrastructure@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  parent: ops
  children: [backstage, other]
  members: [tyler.austgen, nick.maccarthy]